### ISSUE TITLE
Can't use multiple fields to sort

### ISSUE THREAD

**Issue by Kainretsu** [trevorld/Hanzi_Stats#24] opened 2024-08-25 12:57 UTC
selecting more than one field to use for stats doesn't seem to work, writing own
   "fieldToUseForStats": "1", "2" 
makes this error pop up
   "Invalid configuration: JSONDecodeError("Expecting ':' delimiter: line 41 column 5 (char 1157)")"

**Comment by trevorld** [comment] 2024-08-26 03:14
* Closing this issue since it is a duplicate of #10 
* This exact feature isn't currently supported.  You can use "all" to look in all fields otherwise you need to choose "sortField" or the particular number of the field to look in.  Note you can use hacks like editing your decks so your Hanzi field is always the "sortField" or if not the "sortField" it is always the same "nth" field.

**Closed as not planned by trevorld** 2024-08-26 03:14 UTC
Labels: duplicate
